# Generated by Django 3.1.1 on 2020-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='long_url',
            field=models.URLField(max_length=2500),
        ),
    ]
